### ISSUE TITLE
USER STORY2: Limit the booking Per day

### ISSUE THREAD

**Issue by Anthonyrajlucas** [Anthonyrajlucas/django-anto-restaurant#2]
EPIC:  Prevent Double Bookings

As a **customer**, I want to **ensure** that the **table** is **not overbooked for a day**.

**Acceptance Criteria**

- [ ] When a customer selects a time slot and restaurant, the system should check for table availability.
- [ ] If the table is available, the booking should proceed; otherwise, an error message should be shown.

**Task**

- [ ] Design logic to check table availability for the selected time slot.
- [ ] Implement error handling for booking exceeds 25 per day.
